server:
  host: localhost
  port: 8080
  enable_cors: false
path:
  logs: logs
logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    simple:
      format: "%(asctime)s - %(name)s:%(lineno)d - [%(levelname)s] - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
    file:
      class: logging.handlers.TimedRotatingFileHandler
      when: midnight
      backupCount: 90
      level: INFO
      formatter: simple
      filename: main.log
  loggers:
    uvicorn:
      level: INFO
      propagate: yes
      handlers:
        - file
  root:
    level: INFO
    handlers:
      - console
      - file
